FROM python:3.10

WORKDIR /code

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY .env.dev .env

COPY . /code

RUN find /code -name "*.pyc" -delete && find /code -name "__pycache__" -delete

RUN pip install --no-cache-dir -r requirements.txt

ENV ENV=dev
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]